phpcq:
  repositories:
    - https://phpcq.github.io/repository/repository.json
  directories:
    - src
    - tests
  artifact: .phpcq/build
  tools:
    phpunit:
      version: ^9.0
    phpcpd:
      version: ^5.0
    phpmd:
      version: ^2.8.2
    psalm:
      version: ^3.10.0
    composer-require-checker:
      version: ^2.0.0

phpunit:

phpcpd:

phploc:

phpmd:
  ruleset:
    - cleancode
    - codesize
    - controversial
    - design
    - naming
    - unusedcode

psalm:

composer-require-checker:
  config_file: '.composer-require-checker.json'
